//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHSCC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>approach</string>
  <string>bathing after</string>
  <string>bathing during</string>
  <string>coldair</string>
  <string>cover</string>
  <string>dampness</string>
  <string>During riding</string>
  <string>morning rising after</string>
  <string>motion</string>
  <string>night warmth of bed.</string>
  <string>presure riding</string>
  <string>rainy weather</string>
  <string>rest touch rubbuing</string>
  <string>springseasion</string>
  <string>storm</string>
  <string>summer</string>
  <string>Sun heat</string>
  <string>uncover</string>
  <string>wet</string>
  <string>winter</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Modalities {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Modalities"]));
            }
            set {
                this["Modalities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Default</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Symptoms {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Symptoms"]));
            }
            set {
                this["Symptoms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Default</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BodyParts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BodyParts"]));
            }
            set {
                this["BodyParts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Thin</string>
  <string>Yellow</string>
  <string>Watery</string>
  <string>Thick</string>
  <string>White</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Discharge {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Discharge"]));
            }
            set {
                this["Discharge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public ulong RegNo {
            get {
                return ((ulong)(this["RegNo"]));
            }
            set {
                this["RegNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Default</string>\r\n  <string>Other</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Complaints {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Complaints"]));
            }
            set {
                this["Complaints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDir {
            get {
                return ((string)(this["DefaultDir"]));
            }
            set {
                this["DefaultDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color MenuBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuBackColor"]));
            }
            set {
                this["MenuBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long PatID {
            get {
                return ((long)(this["PatID"]));
            }
            set {
                this["PatID"] = value;
            }
        }
    }
}
